export const sidebarLinks = [
    {
        route: '/subscription',
        label: 'Upgrade to Premium',
        premiumLabel: 'Premium',
        imgURL: "/icons/premiumIcon.svg",
        admin: true,
        ambassador: false,
    },
    {
        route: '/',
        label: 'Home',
        imgURL: "/icons/home.svg",
        admin: false,
        ambassador: false,
    },
    {
        route: '/explore',
        label: 'Explore',
        imgURL: '/icons/exploreIcon.svg',
        admin: false,
        ambassador: false,
    },
    {
        route: '/underdevelopment',
        label: 'Take Quiz',
        imgURL: '/icons/quizIcon.svg',
        admin: false,
        ambassador: false,
    }, 
    {
        route: '/stumarket',
        label: 'StuMarket',
        imgURL: '/icons/marketIcon.svg',
        admin: false,
        ambassador: false,
    },
    {
        route: '/upload',
        label: 'Upload Documents',
        imgURL: '/icons/documentIcon.svg',
        admin: false,
        ambassador: true,
    },
    {
        route: '/create-course',
        label: 'Create Course',
        imgURL: '/icons/createIcon.svg',
        admin: false,
        ambassador: true,
    },
    {
        route: '/contact',
        label: 'About & Support',
        imgURL: '/icons/contactIcon.svg',
        admin: false,
        ambassador: false,
    },
];
