type SchoolData = {
    [key: string]: string[];
  };

export const schoolData: SchoolData = {
    "Blekinge Tekniska Högskola (BTH)": [
      "Civilingenjör i AI och maskininlärning, 300 hp",
      "Civilingenjör i datorsäkerhet, 300 hp",
      "Civilingenjör i industriell ekonomi och management, 300 hp",
      "Civilingenjör i marin teknik, 300 hp",
      "Civilingenjör i maskinteknik - produktutveckling, 300 hp",
      "Civilingenjör i mjukvaruutveckling, 300 hp",
      "Civilingenjör i spelteknik, 300 hp",
      "Fysisk planering, 180 hp",
      "Högskoleingenjör i IT-säkerhet, 180 hp",
      "Högskoleingenjör i maskinteknik, 180 hp",
      "Högskoleingenjör i teknisk spelgrafik, 180 hp",
      "Sjuksköterskeprogrammet, 180 hp",
      "Software Engineering, 180 hp",
      "Webbprogrammering, 180 hp",
    ],
  
    "Chalmers Tekniska Högskola": [
      "Arkitektur",
      "Arkitektur och teknik",
      "Tekniskt basår",
      "Automation och mekatronik, 300 hp",
      "Bioteknik, 300 hp",
      "Datateknik, 300 hp",
      "Elektroteknik, 300 hp",
      "Globala system, 300 hp",
      "Industriell ekonomi, 300 hp",
      "Informationsteknik, 300 hp",
      "Kemiteknik med fysik, 300 hp",
      "Kemiteknik, 300 hp",
      "Maskinteknik, 300 hp",
      "Medicinteknik, 300 hp",
      "Samhällsbyggnadsteknik, 300 hp",
      "Teknisk design, 300 hp",
      "Teknisk fysik, 300 hp",
      "Teknisk matematik, 300 hp",
      "Datateknik, 180 hp",
      "Design och produktutveckling, 180 hp",
      "Ekonomi och produktionsteknik, 180 hp",
      "Elektroteknik, 180 hp",
      "Maskinteknik, 180 hp",
      "Mekatronik, 180 hp",
      "Samhällsbyggnadsteknik, 180 hp",
    ],
  
    "Högskolan Dalarna": [
      "Byggteknik och design 180 hp",
      "Byggingenjörsprogram 180 hp",
      "Data Science: Masterprogram 300 hp",
      "Energi - Högskoleingenjörsprogram 180 hp",
      "IT säkerhet och mjukvarutestning 180 hp",
      "Maskinteknik 300 hp",
      "Materialdesign 300 hp",
      "Medicinsk teknik 180 hp",
      "Medicinsk teknik 300 hp",
      "Samhällsbyggnad 300 hp",
      "Teknisk bastermin 180 hp",
      "Tekniskt basår 180 hp",
    ],
  
    "Högskolan i Borås": [
      "Affärsutvecklarprogrammet Bygg och Fastighet, 180 hp",
      "Byggingenjör, 180 hp",
      "Energiingenjör, 180 hp",
      "Industriell ekonomi - affärsingenjör, 180 hp",
      "Industriell ekonomi - arbetsorganisation och ledarskap, 180 hp",
      "Industriell ekonomi - logistikingenjör, 180 hp",
      "IT-ingenjör - digital infrastruktur och cybersäkerhet, 180 hp",
      "Kemiingenjör - tillämpad bioteknik, 180 hp",
      "Maskiningenjör - Automation och AI, 180 hp",
      "Textilingenjörsutbildning, 180 hp",
    ],
  
    "Högskolan i Halmstad": [
      "Byggingenjör, 180 hp",
      "Civilingenjör i datateknik, 300 hp",
      "Civilingenjör i intelligenta system, 300 hp",
      "Civilingenjör i maskinteknik, hållbar design och innovation, 300 hp",
      "Dataingenjör, 180 hp",
      "Elektroingenjör, 180 hp",
      "Ingenjör i hållbar energi, 180 hp",
      "IT-forensik och informationssäkerhet, 180 hp",
      "Mekatronikingenjör, 180 hp",
      "Tillämpad artificiell intelligens (AI), 180 hp",
      "Utvecklingsingenjörsprogrammet, 180 hp",
    ],
  
    "Kungliga Tekniska högskolan (KTH)": [
      "Arkitektutbildning 300 hp",
      "Bioteknik 300 hp",
      "Byggteknik och design 180 hp",
      "Civilingenjör och lärare 300 hp",
      "Datateknik 300 hp",
      "Datateknik, Flemingsberg 180 hp",
      "Datateknik, Kista 180 hp",
      "Design och produktframtagning 300 hp",
      "Elektronik och datorteknik 180 hp",
      "Elektroteknik 180 hp",
      "Elektroteknik 300 hp",
      "Energi och miljö 300 hp",
      "Farkostteknik 300 hp",
      "Fastighet och finans 180 hp",
      "Fastighetsutveckling med fastighetsförmedling 180 hp",
      "Industriell ekonomi 300 hp",
      "Industriell teknik 180 hp",
      "Industriell teknik och hållbarhet 300 hp",
      "Informations- och kommunikationsteknik 180 hp",
      "Informationsteknik 300 hp",
      "Kemiteknik 180 hp",
      "Maskinteknik 300 hp",
      "Materialdesign 300 hp",
      "Medicinsk teknik 180 hp",
      "Medicinsk teknik 300 hp",
      "Medieteknik 300 hp",
      "Samhällsbyggnad 300 hp",
      "Teknik och ekonomi 180 hp",
      "Teknisk fysik 300 hp",
      "Teknisk kemi 300 hp",
      "Teknisk matematik 300 hp",
    ],
  
    "Linnéuniversitetet": [
      "Byggnadsutformning, 180 hp",
      "Byggteknik, 180 hp",
      "Civilingenjör i mjukvaruteknik, 300 hp",
      "Civilingenjör i teknisk matematik, 300 hp",
      "Datateknik, 180 hp",
      "Driftteknikerprogrammet, 120 hp",
      "Drift- och underhållsteknik, 180 hp",
      "Elektroteknik, 180 hp",
      "Energi och miljö, 180 hp",
      "Fysikerprogrammet, 180 hp",
      "Industriell ekonomi, 180 hp",
      "Maskinteknik, inriktning produktutveckling, 180 hp",
      "Matematikerprogrammet, 180 hp",
      "Mjukvaruteknik, 180 hp",
      "Sjöingenjör, 180 hp",
      "Skogskandidatprogrammet, 180 hp",
    ],
  
    "Luleå tekniska universitet": [
      "Hållbar energiteknik, 300 hp",
      "Industriell ekonomi, 300 hp",
      "Hållbar process- och kemiteknik, 300 hp",
      "Teknisk design, 300 hp",
      "Teknisk fysik och elektroteknik, 300 hp",
      "Väg- och vattenbyggnad, 300 hp",
      "Maskinteknik, 300 hp",
      "Materialteknik, 300 hp",
      "Arkitektur, 300 hp",
      "Datateknik, 300 hp",
      "Rymdteknik, 300 hp",
      "Öppen ingång, 300 hp",
      "Tillämpad artificiell intelligens, 300 hp",
      "Naturresursteknik, 300 hp",
      "Maskinteknik, 180 hp",
      "Underhållsteknik, 180 hp",
      "Bergteknik, 180 hp",
      "Bilsystemteknik, 180 hp",
      "Energiteknik, 180 hp",
      "Elkraftteknik, 180 hp",
      "Datateknik, 180 hp",
    ],
  
    "Lunds universitet": [
      "Bioteknik, 300 hp",
      "Ekosystemteknik, 300 hp",
      "Industriell ekonomi, 300 hp",
      "Maskinteknik, 300 hp",
      "Maskinteknik - teknisk design, 300 hp",
      "Medicin och teknik, 300 hp",
      "Risk, säkerhet och krishantering",
      "Teknisk fysik, 300 hp",
      "Teknisk nanovetenskap, 300 hp",
      "Elektroteknik, 300 hp",
      "Informations- och kommunikationsteknik, 300 hp",
      "Kemiteknik, 300 hp",
      "Lantmäteriteknik, 300 hp",
      "Maskinteknik, 300 hp",
      "Teknisk fysik, 300 hp",
      "Teknisk matematik, 300 hp",
      "Datateknik, 180 hp",
      "Logistics service management, 180 hp",
    ],
  
    "Mittuniversitetet": [
      "Additiv tillverkning - högskoleingenjör maskinteknik, 180 hp",
      "Automationsingenjör, 180 hp",
      "Byggingenjör Hållbart byggande, 180 hp",
      "Civilingenjör i datateknik, 300 hp",
      "Civilingenjör i elektroteknik, 300 hp",
      "Civilingenjör i industriell ekonomi, 300 hp",
      "Civilingenjör i teknisk design, 300 hp",
      "Civilingenjör i teknisk fysik, 300 hp",
      "Civilingenjör i teknisk kemi, 300 hp",
      "Civilingenjörsutbildning i teknisk kemi Mittuniversitetet-KTH, 300 hp",
      "Ekoingenjör, 180 hp",
      "Sportteknologi - högskoleingenjör produktutveckling, 180 hp",
    ],

    "Other School":[
        "Other",
    ],
  };
  