type Course = {
  name: string;
  codes: string[];
};

type SchoolData = {
  [key: string]: Course[];
};

export const schoolData: SchoolData = {
  "Blekinge Tekniska Högskola (BTH)": [
    { name: "Civilingenjör i AI och maskininlärning, 300 hp", codes: [] },
    { name: "Civilingenjör i datorsäkerhet, 300 hp", codes: [] },
    { name: "Civilingenjör i industriell ekonomi och management, 300 hp", codes: [] },
    { name: "Civilingenjör i marin teknik, 300 hp", codes: [] },
    { name: "Civilingenjör i maskinteknik - produktutveckling, 300 hp", codes: [] },
    { name: "Civilingenjör i mjukvaruutveckling, 300 hp", codes: [] },
    { name: "Civilingenjör i spelteknik, 300 hp", codes: [] },
    { name: "Fysisk planering, 180 hp", codes: [] },
    { name: "Högskoleingenjör i IT-säkerhet, 180 hp", codes: [] },
    { name: "Högskoleingenjör i maskinteknik, 180 hp", codes: [] },
    { name: "Högskoleingenjör i teknisk spelgrafik, 180 hp", codes: [] },
    { name: "Sjuksköterskeprogrammet, 180 hp", codes: [] },
    { name: "Software Engineering, 180 hp", codes: [] },
    { name: "Webbprogrammering, 180 hp", codes: [] },
  ],

  "Chalmers Tekniska Högskola": [
    { name: "Arkitektur", codes: [] },
    { name: "Arkitektur och teknik", codes: [] },
    { name: "Tekniskt basår", codes: ["MVE426", "SEE180", "MVE285", "IMS145", "KBT185", "TIF410", "LET924", "MVE725", "TIF410"] },
    { name: "Automation och mekatronik, 300 hp", codes: [] },
    { name: "Bioteknik, 300 hp", codes: [] },
    { name: "Datateknik, 300 hp", codes: [] },
    { name: "Elektroteknik, 300 hp", codes: [] },
    { name: "Globala system, 300 hp", codes: [] },
    { name: "Industriell ekonomi, 300 hp", codes: [] },
    { name: "Informationsteknik, 300 hp", codes: [] },
    { name: "Kemiteknik med fysik, 300 hp", codes: [] },
    { name: "Kemiteknik, 300 hp", codes: [] },
    { name: "Maskinteknik, 300 hp", codes: [] },
    { name: "Medicinteknik, 300 hp", codes: [] },
    { name: "Samhällsbyggnadsteknik, 300 hp", codes: [] },
    { name: "Teknisk design, 300 hp", codes: [] },
    { name: "Teknisk fysik, 300 hp", codes: [] },
    { name: "Teknisk matematik, 300 hp", codes: [] },
    { name: "Datateknik, 180 hp", codes: ["MVE675", "MVE545", "LEU470", "EDA387", "TDA452", "DAT610", "LEU432", "TDA352", "LEU483", "LSP581", "DAT341", "DAT565", "TDA384", "LET627", "TDA567", "TDA596", "EDA234", "MVE535", "DAT390", "TDA357", "EDA093", "DAT151", "EDA264", "CLS050", "TMV211","DAT055", "DAT050", "LEU237", "SSY326", "EDA387", "TDA452", "DAT610", "LMA521", "DAT257", "TDA352", "FFR102", "DAT565", "TDA384", "TDA567", "LMA201", "TDA596", "EDA234", "EDA322", "DAT390", "DAT356", "LEU062", "LMU450", "TDA357", "DAT326", "EDA093", "DAT151", "EDA264", "TMV211", "DAT495","DAT050", "EDA387", "LMTX38", "TDA452", "DAT610", "LSP127", "DAT068", "LMA521", "DAT076", "DAT257", "TDA352", "TEK486", "DAT341", "DAT565", "TDA384", "TDA567", "SSY011", "LMA201", "TDA596", "EDA234", "EDA322", "DAT356", "EENX20", "LEU062", "LMU450", "TDA357", "DAT326", "EDA093", "DAT151", "EDA264", "LMA017", "DAT495"] },
    { name: "Design och produktutveckling, 180 hp", codes: [] },
    { name: "Ekonomi och produktionsteknik, 180 hp", codes: [] },
    { name: "Elektroteknik, 180 hp", codes: ["MVE675", "MVE545", "LEU470", "ENM061", "ENM097", "LEU432", "LEU483", "LSP581", "TME095", "EDA234", "MVE535", "DAT390", "LET086", "MTT060", "ENM056", "ENM052", "MTT035", "SSY305", "CLS050","SSY326", "ENM061", "ENM097", "SEE035", "FFR102", "TME095", "LMA201", "EDA234", "LEU236", "EDA322", "DAT390", "ENM056", "LET271", "EEK565", "LEU062", "ENM052", "RRY011", "LMU450", "SSY020", "LMTX38", "ENM061", "ENM097", "LSP127", "DAT068", "EEN225", "EEN095", "SSY251", "SSY011", "TME095", "LMA201", "EDA234", "EDA322", "MCCX05", "MTT060", "ENM056", "EENX20", "LEU340", "LEU062", "ENM052", "LMU450", "MTT035", "SEEX20", "LET564", "SSY305", "LMA017"] },
    { name: "Maskinteknik, 180 hp", codes: ["MMS275", "MMS050", "LMA401", "MVE645", "LMU421", "LMT202", "PPU127", "MVE580", "TME255", "PPU201", "LMA522", "MMS050", "LMS893", "TEK720", "PPU196", "SSY295", "LMA224", "IMS026", "IMS100", "PPU201", "IMS045", "LMU305", "LMA522", "IMSX20", "SEE020", "MTT126", "MMS050", "LMS586", "TEK720", "LMU102", "LMT108", "SSY295", "MTF115", "MTF053", "LMT211", "IMS020", "MMF092", "MMSX25", "LMA224", "TEKX01", "LMA017", "LMU056", "IMS095"] },
    { name: "Mekatronik, 180 hp", codes: ["EEN030", "LEU432", "LMA401", "MVE580", "LEU471", "TME221", "LEU076", "LEU481", "LMT212", "SSY020", "LEU236", "MMS125", "DAT390", "EEN105", "SSY326", "EEN090", "IMS060", "IMS080", "DAT050", "EEN095", "LMA017", "LMU055", "SSY011", "LMU433", "SSY251", "EDA322", "LEU340", "LMA224", "LMA522", "LMT834", "TEK725"] },
    { name: "Samhällsbyggnadsteknik, 180 hp", codes: [] },
  ],

  "Högskolan Dalarna": [
    { name: "Byggteknik och design 180 hp", codes: [] },
    { name: "Byggingenjörsprogram 180 hp", codes: [] },
    { name: "Data Science: Masterprogram 300 hp", codes: [] },
    { name: "Energi - Högskoleingenjörsprogram 180 hp", codes: [] },
    { name: "IT säkerhet och mjukvarutestning 180 hp", codes: [] },
    { name: "Maskinteknik 300 hp", codes: [] },
    { name: "Materialdesign 300 hp", codes: [] },
    { name: "Medicinsk teknik 180 hp", codes: [] },
    { name: "Medicinsk teknik 300 hp", codes: [] },
    { name: "Samhällsbyggnad 300 hp", codes: [] },
    { name: "Teknisk bastermin 180 hp", codes: [] },
    { name: "Tekniskt basår 180 hp", codes: [] },
  ],

  "Högskolan i Borås": [
    { name: "Affärsutvecklarprogrammet Bygg och Fastighet, 180 hp", codes: [] },
    { name: "Byggingenjör, 180 hp", codes: [] },
    { name: "Energiingenjör, 180 hp", codes: [] },
    { name: "Industriell ekonomi - affärsingenjör, 180 hp", codes: [] },
    { name: "Industriell ekonomi - arbetsorganisation och ledarskap, 180 hp", codes: [] },
    { name: "Industriell ekonomi - logistikingenjör, 180 hp", codes: [] },
    { name: "IT-ingenjör - digital infrastruktur och cybersäkerhet, 180 hp", codes: [] },
    { name: "Kemiingenjör - tillämpad bioteknik, 180 hp", codes: [] },
    { name: "Maskiningenjör - Automation och AI, 180 hp", codes: [] },
    { name: "Textilingenjörsutbildning, 180 hp", codes: [] },
  ],

  "Högskolan i Halmstad": [
    { name: "Byggingenjör, 180 hp", codes: [] },
    { name: "Civilingenjör i datateknik, 300 hp", codes: [] },
    { name: "Civilingenjör i intelligenta system, 300 hp", codes: [] },
    { name: "Civilingenjör i maskinteknik, hållbar design och innovation, 300 hp", codes: [] },
    { name: "Dataingenjör, 180 hp", codes: [] },
    { name: "Elektroingenjör, 180 hp", codes: [] },
    { name: "Ingenjör i hållbar energi, 180 hp", codes: [] },
    { name: "IT-forensik och informationssäkerhet, 180 hp", codes: [] },
    { name: "Mekatronikingenjör, 180 hp", codes: [] },
    { name: "Tillämpad artificiell intelligens (AI), 180 hp", codes: [] },
    { name: "Utvecklingsingenjörsprogrammet, 180 hp", codes: [] },
  ],

  "Kungliga Tekniska högskolan (KTH)": [
    { name: "Arkitektutbildning 300 hp", codes: [] },
    { name: "Bioteknik 300 hp", codes: [] },
    { name: "Byggteknik och design 180 hp", codes: [] },
    { name: "Civilingenjör och lärare 300 hp", codes: [] },
    { name: "Datateknik 300 hp", codes: [] },
    { name: "Datateknik, Flemingsberg 180 hp", codes: [] },
    { name: "Datateknik, Kista 180 hp", codes: [] },
    { name: "Design och produktframtagning 300 hp", codes: [] },
    { name: "Elektronik och datorteknik 180 hp", codes: [] },
    { name: "Elektroteknik 180 hp", codes: [] },
    { name: "Elektroteknik 300 hp", codes: [] },
    { name: "Energi och miljö 300 hp", codes: [] },
    { name: "Farkostteknik 300 hp", codes: [] },
    { name: "Fastighet och finans 180 hp", codes: [] },
    { name: "Fastighetsutveckling med fastighetsförmedling 180 hp", codes: [] },
    { name: "Industriell ekonomi 300 hp", codes: [] },
    { name: "Industriell teknik 180 hp", codes: [] },
    { name: "Industriell teknik och hållbarhet 300 hp", codes: [] },
    { name: "Informations- och kommunikationsteknik 180 hp", codes: [] },
    { name: "Informationsteknik 300 hp", codes: [] },
    { name: "Kemiteknik 180 hp", codes: [] },
    { name: "Maskinteknik 300 hp", codes: [] },
    { name: "Materialdesign 300 hp", codes: [] },
    { name: "Medicinsk teknik 180 hp", codes: [] },
    { name: "Medicinsk teknik 300 hp", codes: [] },
    { name: "Medieteknik 300 hp", codes: [] },
    { name: "Samhällsbyggnad 300 hp", codes: [] },
    { name: "Teknik och ekonomi 180 hp", codes: [] },
    { name: "Teknisk fysik 300 hp", codes: [] },
    { name: "Teknisk kemi 300 hp", codes: [] },
    { name: "Teknisk matematik 300 hp", codes: [] },
  ],

  "Linnéuniversitetet": [
    { name: "Byggnadsutformning, 180 hp", codes: [] },
    { name: "Byggteknik, 180 hp", codes: [] },
    { name: "Civilingenjör i mjukvaruteknik, 300 hp", codes: [] },
    { name: "Civilingenjör i teknisk matematik, 300 hp", codes: [] },
    { name: "Datateknik, 180 hp", codes: [] },
    { name: "Driftteknikerprogrammet, 120 hp", codes: [] },
    { name: "Drift- och underhållsteknik, 180 hp", codes: [] },
    { name: "Elektroteknik, 180 hp", codes: [] },
    { name: "Energi och miljö, 180 hp", codes: [] },
    { name: "Fysikerprogrammet, 180 hp", codes: [] },
    { name: "Industriell ekonomi, 180 hp", codes: [] },
    { name: "Maskinteknik, inriktning produktutveckling, 180 hp", codes: [] },
    { name: "Matematikerprogrammet, 180 hp", codes: [] },
    { name: "Mjukvaruteknik, 180 hp", codes: [] },
    { name: "Sjöingenjör, 180 hp", codes: [] },
    { name: "Skogskandidatprogrammet, 180 hp", codes: [] },
  ],

  "Luleå tekniska universitet": [
    { name: "Hållbar energiteknik, 300 hp", codes: [] },
    { name: "Industriell ekonomi, 300 hp", codes: [] },
    { name: "Hållbar process- och kemiteknik, 300 hp", codes: [] },
    { name: "Teknisk design, 300 hp", codes: [] },
    { name: "Teknisk fysik och elektroteknik, 300 hp", codes: [] },
    { name: "Väg- och vattenbyggnad, 300 hp", codes: [] },
    { name: "Maskinteknik, 300 hp", codes: [] },
    { name: "Materialteknik, 300 hp", codes: [] },
    { name: "Arkitektur, 300 hp", codes: [] },
    { name: "Datateknik, 300 hp", codes: [] },
    { name: "Rymdteknik, 300 hp", codes: [] },
    { name: "Öppen ingång, 300 hp", codes: [] },
    { name: "Tillämpad artificiell intelligens, 300 hp", codes: [] },
    { name: "Naturresursteknik, 300 hp", codes: [] },
    { name: "Maskinteknik, 180 hp", codes: [] },
    { name: "Underhållsteknik, 180 hp", codes: [] },
    { name: "Bergteknik, 180 hp", codes: [] },
    { name: "Bilsystemteknik, 180 hp", codes: [] },
    { name: "Energiteknik, 180 hp", codes: [] },
    { name: "Elkraftteknik, 180 hp", codes: [] },
    { name: "Datateknik, 180 hp", codes: [] },
  ],

  "Lunds universitet": [
    { name: "Bioteknik, 300 hp", codes: [] },
    { name: "Ekosystemteknik, 300 hp", codes: [] },
    { name: "Industriell ekonomi, 300 hp", codes: [] },
    { name: "Maskinteknik, 300 hp", codes: [] },
    { name: "Maskinteknik - teknisk design, 300 hp", codes: [] },
    { name: "Medicin och teknik, 300 hp", codes: [] },
    { name: "Risk, säkerhet och krishantering", codes: [] },
    { name: "Teknisk fysik, 300 hp", codes: [] },
    { name: "Teknisk nanovetenskap, 300 hp", codes: [] },
    { name: "Elektroteknik, 300 hp", codes: [] },
    { name: "Informations- och kommunikationsteknik, 300 hp", codes: [] },
    { name: "Kemiteknik, 300 hp", codes: [] },
    { name: "Lantmäteriteknik, 300 hp", codes: [] },
    { name: "Maskinteknik, 300 hp", codes: [] },
    { name: "Teknisk fysik, 300 hp", codes: [] },
    { name: "Teknisk matematik, 300 hp", codes: [] },
    { name: "Datateknik, 180 hp", codes: [] },
    { name: "Logistics service management, 180 hp", codes: [] },
  ],

  "Mittuniversitetet": [
    { name: "Additiv tillverkning - högskoleingenjör maskinteknik, 180 hp", codes: [] },
    { name: "Automationsingenjör, 180 hp", codes: [] },
    { name: "Byggingenjör Hållbart byggande, 180 hp", codes: [] },
    { name: "Civilingenjör i datateknik, 300 hp", codes: [] },
    { name: "Civilingenjör i elektroteknik, 300 hp", codes: [] },
    { name: "Civilingenjör i industriell ekonomi, 300 hp", codes: [] },
    { name: "Civilingenjör i teknisk design, 300 hp", codes: [] },
    { name: "Civilingenjör i teknisk fysik, 300 hp", codes: [] },
    { name: "Civilingenjör i teknisk kemi, 300 hp", codes: [] },
    { name: "Civilingenjörsutbildning i teknisk kemi Mittuniversitetet-KTH, 300 hp", codes: [] },
    { name: "Ekoingenjör, 180 hp", codes: [] },
    { name: "Sportteknologi - högskoleingenjör produktutveckling, 180 hp", codes: [] },
  ],

  "Other School": [
    { name: "Other", codes: [] },
  ],
};
